---
- hosts: all
  connection: local
  become: root
  tasks:
    - name: Preparing to install pwquality module
      apt:
        update_cache: yes
        upgrade: full
  
    - name: Installing pwquality module
      apt:
        name: libpam-pwquality
      
    - name: Configuring pwquality module
      pamd:
        name: common-password
        type: password
        control: requisite
        module_path: pam_pwquality.so
        module_arguments: 'usercheck=1 enforce_for_root retry=3'
        state: updated
