---
- hosts: all
  remote_user: root
  tasks:
    - name: Hardening the sshd
      lineinfile:
        path: /etc/hosts.deny
        line: "sshd: ALL EXCEPT LOCAL, {{ ansible_env['SSH_CLIENT'].split()[0] }}"