---
- hosts: all
  remote_user: root
  tasks:
    - name: Installing pwquality module
      apt:
        name: libpam-pwquality
        update_cache: yes
      
    - name: Configuring pwquality module
      pamd:
        name: common-password
        type: password
        control: requisite
        module_path: pam_pwquality.so
        module_arguments: 'usercheck=1 enforce_for_root retry=3'
        state: updated