---
- hosts: all
  remote_user: root
  tasks: 
    - name: Installing pwquality module
      apt:
        name: libpam-pwquality
        update_cache: yes

    - name: Configuring pwquality module
      lineinfile: 
        path: /etc/security/pwquality.conf
        regexp: "{{ item.pattern }}"
        line: "{{ item.data }}"
        state: present
      loop:
        - {pattern: 'usercheck', data: 'usercheck=1' }
        - {pattern: 'enforce_for_root', data: 'enforce_for_root' }
        - {pattern: 'retry', data: 'retry=3' }